version: "3"

services:
  front:
    build: ./front
#    image: node:16-alpine3.11
#    volumes:
#      - ./front:/app
#    working_dir: /app
#    command: sh -c "npm i && npm run serve"
    ports:
      - 8080:8080
#    environment:
#      - PORT=8080
  back:
    build: ./back
#    command: go run read.go server.go
    ports:
      - 3000:3000
#    environment:
#      - PORT=3000

